pluginManagement {
    repositories {
        gradlePluginPortal()

        maven {
            name = "GTCEu Maven"
            url = uri("https://maven.gtceu.com")
            content {
                includeGroup("com.gregtechceu.gtceu")
            }
        }
        maven {
            name = "parchment"
            url = uri("https://maven.parchmentmc.org")
        }
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
