
modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"


[[mods]]
    modId = "rubberdt"
    version = "1.0"
    displayName = "RubberDynamicTrees"
    authors = "Restor"
    description = '''Rubber tree for DynamicTrees'''

[[dependencies.rubberdt]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.rubberdt]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.rubberdt]]
    modId = "dynamictrees"
    mandatory = true
    versionRange="[1.3.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.rubberdt]]
    modId = "gtceu"
    mandatory = true
    versionRange="[1.6.4,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.rubberdt]]
    modId = "rubberdt"
    mandatory = true
    versionRange="[1.0,)"
    ordering = "AFTER"
    side = "BOTH"